### ISSUE TITLE
Time Dilation

### ISSUE THREAD

**Issue by teamcoltra** [jtauber/mars-clock#3]
Wouldn't Mars have it's own seconds due to gravitational time dilation (and perhaps it's velocity vs Earth's)? Is this taken into consideration?

**Comment by edgar-bonet** [comment]
A clock on the surface of Mars would indeed tick faster than an identical clock on Earth, by about 5.66e-9 (0.18 seconds per year), mostly due to the gravitational field of the Sun. This is not taken into account, and doesn't have to, as the formulas used are based on [terrestrial time](https://en.wikipedia.org/wiki/Terrestrial_Time), not on an hypothetical Mars analog of terrestrial time (proper time on the surface of Mars).

The relativistic corrections could only be relevant if you were to take your Web browser to Mars, and run the JavaScript code there. A computer clock, however, is not accurate enough for the correction to be meaningful.
